name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream
    runs-on: ubuntu-latest
    if: github.repository_owner == '0ozzzii'

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: komari-monitor/komari
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false